# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./controlwidget.h \
    ./debug.h \
    ./mainwindow.h \
    ./3rdparty/qtsingleapplication/src/qtlocalpeer.h \
    ./3rdparty/qtsingleapplication/src/qtsingleapplication.h \
    ./search.h \
    ./searchmodel.h \
    ./searchview.h \
    ./svgsplashscreen.h
SOURCES += ./controlwidget.cpp \
    ./main.cpp \
    ./mainwindow.cpp \
    ./3rdparty/qtsingleapplication/src/qtlocalpeer.cpp \
    ./3rdparty/qtsingleapplication/src/qtsingleapplication.cpp \
    ./search.cpp \
    ./searchmodel.cpp \
    ./searchview.cpp \
    ./svgsplashscreen.cpp
FORMS += ./controlwidget.ui \
    ./mainwindow.ui
RESOURCES += mainwindow.qrc
