# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./playlistitem.h \
    ./playlistitem_global.h \
    ./youtubeitem.h \
    ./localitem.h
SOURCES += ./youtubeitem.cpp \
    ./playlistitem.cpp \
    ./localitem.cpp
