# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += playlistitem/playlistitem.h \
    playlistitem/playlistitem_global.h \
    playlistitem/youtubeitem.h \
    playlistitem/localitem.h
SOURCES += playlistitem/youtubeitem.cpp \
    playlistitem/playlistitem.cpp \
    playlistitem/localitem.cpp
