# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./playlist.h \
    ./playlistitem.h \
    ./playlistmodel.h

#Source files
SOURCES += ./playlist.cpp \
    ./playlistitem.cpp \
    ./playlistmodel.cpp
