# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./playlist_export.h \
    ./playlist_global.h \
    ./playlistdelegate.h \
    ./playlistitem.h \
    ./playlistmodel.h \
    ./playlistview.h
SOURCES += ./playlistdelegate.cpp \
    ./playlistitem.cpp \
    ./playlistmodel.cpp \
    ./playlistview.cpp
RESOURCES += ./playlist.qrc
