# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./playlist_global.h \
    ./playlistdelegate.h \
    ./playlistitem.h \
    ./playlistmodel.h \
    ./playlistview.h

#Source files
SOURCES += ./playlistdelegate.cpp \
    ./playlistitem.cpp \
    ./playlistmodel.cpp \
    ./playlistview.cpp
