# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./player.h \
    ./player_global.h \
    ./debug.h
SOURCES += ./player.cpp
