# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./player.h \
    ./player_global.h

#Source files
SOURCES += ./player.cpp
