# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./player.h \
    ./player_global.h \
    ./message.h \
    ./messagehandler.h

#Source files
SOURCES += ./player.cpp \
    ./message.cpp \
    ./messagehandler.cpp
