# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./debug.h \
    ./player_global.h \
    ./qgstplayer.h \
    ./qgstplayer_p.h \
    ./youtubeplayer.h
SOURCES += ./qgstplayer.cpp \
    ./youtubeplayer.cpp
