# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./DShowPlayer/qtdirectaudio.h \
    ./DShowPlayer/qtdirectaudio_p.h \
    ./GstPlayer/qgstplayer.h \
    ./GstPlayer/qgstplayer_p.h \
    ./YoutubePlayer/youtubeplayer.h
SOURCES += ./DShowPlayer/qtdirectaudio.cpp \
    ./GstPlayer/qgstplayer.cpp \
    ./YoutubePlayer/youtubeplayer.cpp
