# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./application.h \
    ./controlbutton.h \
    ./controlslider.h \
    ./controlwidget.h \
    ./debug.h \
    ./mainwindow.h \
    ./3rdparty/qtsingleapplication/src/qtlocalpeer.h \
    ./3rdparty/qtsingleapplication/src/qtsingleapplication.h \
    ./youtubesearchmodel.h \
    ./svgsplashscreen.h \
    ./youtubesearchview.h
SOURCES += ./application.cpp \
    ./controlbutton.cpp \
    ./controlslider.cpp \
    ./controlwidget.cpp \
    ./main.cpp \
    ./mainwindow.cpp \
    ./3rdparty/qtsingleapplication/src/qtlocalpeer.cpp \
    ./3rdparty/qtsingleapplication/src/qtsingleapplication.cpp \
    ./youtubesearchmodel.cpp \
    ./svgsplashscreen.cpp \
    ./youtubesearchview.cpp
FORMS += ./mainwindow.ui
RESOURCES += mainwindow.qrc
