#ifndef QTDIRECTAUDIO_GLOBAL_H
#define QTDIRECTAUDIO_GLOBAL_H

#include <Qt/qglobal.h>

#ifdef QTDIRECTAUDIO_LIB
# define QTDIRECTAUDIO_EXPORT Q_DECL_EXPORT
#else
# define QTDIRECTAUDIO_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDIRECTAUDIO_GLOBAL_H
