# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./qtdirectaudio.h \
    ./qtdirectaudio_global.h \
    ./qtdirectaudio_p.h
SOURCES += ./qtdirectaudio.cpp
